model:
  name: "huawei-noah/TinyBERT_General_4L_312D"
  num_labels: 6
  max_length: 512

training:
  num_epochs: 3
  batch_size: 16
  learning_rate: 2e-5
  warmup_steps: 500
  weight_decay: 0.01
  output_dir: "./results"
  logging_dir: "./logs"

data:
  test_size: 0.2
  random_state: 42

optuna:
  n_trials: 5
